config/routes.rb
LogViewer::Application.routes.draw do
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/ok"
  get "static_pages/deprecate"
  get "static_pages/parameter"
  get "static_pages/get"
  get "static_pages/put"
  get "static_pages/index"
  get "logs/index"
  get "logs/search"

root 'static_pages#index'
end

app/models/log.rb
class Log < ActiveRecord::Base
    def self.load_logs(log_file,delete_logs)
	    puts "***** Started Log.load_logs *************"

		guid = nil
		last_guid = nil
		last_text = nil
		details = nil
		text = nil
		sequence = 0

		if delete_logs
			puts"  deleting TempLog"		
			TempLog.delete_all
		end

		File.foreach(log_file){
			|log|
			
			# look for "[guid] text"
			m = /\[(\S*)\]\s(.*)/
			mData = m.match log
			if mData
				guid=mData[1]
				text=mData[2]
			else
				guid = last_guid
				text = log
			end
			
			# Write to Temp_Logs
			@tl = TempLog.new
			@tl.guid = guid
			@tl.sequence = sequence
			@tl.text = text
			@tl.save		

			sequence = sequence + 1
			last_guid = guid
		}
		puts ("loaded " + sequence.to_s + " log entries")
		
		if delete_logs
			puts"  deleting Log"		
			Log.delete_all
		end
			
		last_guid=nil
		TempLog.order(:guid,:sequence).each do |tempLog|
			guid = tempLog.guid
			if guid == last_guid
				if !details
					details = tempLog.text
				else
					details = details + "\n" + tempLog.text
				end
			else
				if last_guid != nil
			   		textArray = text.split(" ")
					#Saving Log Entry
					@l = Log.new
					@l.guid = last_guid
					@l.string_started = textArray[0]
					@l.keyword = textArray[1]
					@l.url = textArray[2]
					@l.string_for = textArray[3]
					@l.ip = textArray[4]
					@l.string_at = textArray[5]
					@l.date = textArray[6]
					@l.time = textArray[7]
					@l.zone = textArray[8]
					@l.details = details
					@l.save		
				end
			text = tempLog.text
			details = nil
			end
		
			last_guid = guid
		end
	end
end

app/models/temp_log.rb
class TempLog < ActiveRecord::Base
	def TempLog.dosomething
			puts "in do something"
		TempLog.find_each  do |tempLog|
			puts "tempLog = "
			puts tempLog.id
			puts "tempLog.guid = "
			puts tempLog.guid
			puts "tempLog.text = "
			puts tempLog.text
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
	def index
		delete_logs = true
		load_logs = true
		log_file = "/home/student/LogViewer/sourceData/sample.log"

		if load_logs 
			Log.load_logs(log_file,delete_logs)
		end
	
		# Loading up the logs table into a variable to be used on the view
		@LogsFromDb = Log.all

		@queryLog = Log.new
	end
	
	def search
		@sql = nil
		@show = Array.new
		add_item( 'guid',params[:guid] )
		add_item( 'details',params[:details] )
		add_item( 'keyword',params[:keyword] )
		add_item( 'url',params[:url] )
		add_item( 'ip',params[:ip] )
		add_item( 'date',params[:date] )
		add_item( 'time',params[:time] )
				
		puts "-----------------------------------------------"
		puts "search SQL:"
		puts @sql
		if @sql == nil
			puts "empty search"
			@searchResults = Log.all
			return
		end

		@searchResults = Log.find_by_sql(@sql)
		puts "-----------------------------------------------"
	end

	def add_clause( sub_clause )
		if @sql == nil
			@sql = "select * from logs where " + sub_clause
		else
			@sql = @sql + ' and ' + sub_clause
		end
	end

	def add_item( item_name, item )
		if !item || item.length == 0
			return
		end
		add_clause (item_name + " like '%" + item + "%'")
		@show << (item_name + ": " + item)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div align="center">
<h1>LogViewer</h1>
<%= link_to 'Home',static_pages_index_path %>
<%= link_to 'About',static_pages_about_path %>
<%= link_to 'Contact', static_pages_contact_path %>
<%= yield %>
</div>
</body>
</html>

app/views/logs/_form.html.erb
<%= form_tag("/logs/search", method: "get") do %>
<table>
    <tr>
        <td>
            <%= label_tag(:guid, "Search for GUID:") %>
        </td>
        <td>
            <%= text_field_tag(:guid) %>
        </td>
    </tr>
    <tr>
        <td>
            <%= label_tag(:details, "Search for DETAILS:") %>
        </td>
        <td>
            <%= text_field_tag(:details) %>
        </td>
    </tr>
    <tr>
        <td>
            <%= label_tag(:keyword, "Search for KEYWORD:") %>
        </td>
        <td>
            <%= text_field_tag(:keyword) %>
        </td>
    </tr>
    <tr>
        <td>
            <%= label_tag(:url, "Search for URL:") %>
        </td>
        <td>
            <%= text_field_tag(:url) %>
        </td>
    </tr>
    <tr>
        <td>
            <%= label_tag(:ip, "Search for IP:") %>
        </td>
        <td>
            <%= text_field_tag(:ip) %>
        </td>
    </tr>
    <tr>
        <td>
            <%= label_tag(:date, "Search for Date:") %>
        </td>
        <td>
            <%= text_field_tag(:date) %>
        </td>
    </tr>
    <tr>
        <td>
            <%= label_tag(:time, "Search for Time:") %>
        </td>
        <td>
            <%= text_field_tag(:time) %>
        </td>
    </tr>
</table>
  <%= submit_tag("Search") %>
<% end %>

app/views/logs/index.html.erb
<!-- 
<table border="1">
	<tr>
		<th><b><u>guid</u></b></th>
		<th><b><u>sequence</u></b></th>
		<th><b><u>text</u></b></th>
	</tr>

<% TempLog.order(:guid,:sequence).each do |log| %> 
  <tr>
	 <td><%= log.guid %></td>
	 <td><%= log.sequence %></td>
	 <td><%= log.text %></td>
</tr>
<% end %>
</table> -->

<h1> Querying </h1>
      <%= render 'form' %>

app/views/logs/search.html.erb
<h1>Search Results</h1>
      <%= render 'form' %>


<% @show.each { |param| %> 
	 <li><%= param %></li>
<% } %>


<table border="1">
	<tr>
		<th><b><u>GUID</u></b></th>
		<th><b><u>DETAILS</u></b></th>
		<th><b><u>KEYWORD</u></b></th>
		<th><b><u>URL</u></b></th>
		<th><b><u>IP</u></b></th>
		<th><b><u>DATE</u></b></th>
		<th><b><u>TIME</u></b></th>
		<th><b><u>ZONE</u></b></th>
	</tr>
<% @searchResults.each do |log| %> 
  <tr>
	 <td><%= log.guid %></td>
	 <td><%= log.details %></td>
	 <td><%= log.keyword %></td>
	 <td><%= log.url %></td>
	 <td><%= log.ip %></td>
	 <td><%= log.date %></td>
	 <td><%= log.time %></td>
	 <td><%= log.zone %></td>
</tr>
<% end %>
</table>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Simple Rails Log Viewer Version 0.1</p>

app/views/static_pages/contact.html.erb
	<h1>Contact</h1>
<p>Peter L. Harms</p>
<p>peterlharms@gmail.com</p>

app/views/static_pages/index.html.erb
<p>Click the Link Below to Import Logs into the Database</p>
<p><%= link_to 'Import', logs_index_path %> </p>